
before_script:
  - apt-get update -qq && apt-get install -y -qq gcc g++ wget bsdtar > /dev/null 2>&1
  - mkdir -v toolchains
  - wget https://downloads.arduino.cc/arduino-nightly-linux64.tar.xz
  - sh -c "cd toolchains && tar -xJf ../arduino-nightly-linux64.tar.xz"
  - rm -r -f arduino-nightly-linux64.tar.xz

arduinoplatform_and_tests:
  script:
    - mkdir arduinoplatform-gcc-builddir
    - sh -c "cd arduinoplatform-gcc-builddir && CC=/usr/bin/gcc CXX=/usr/bin/g++ LD=/usr/bin/g++ ../configure -platform=avr -prefix=$PWD/bin -modules=arduino -platformcc=$PWD/toolchains/arduino-nightly/hardware/tools/avr/bin/avr-gcc -platformcxx=$PWD/toolchains/arduino-nightly/hardware/tools/avr/bin/avr-g++ -platformld=$PWD/toolchains/arduino-nightly/hardware/tools/avr/bin/avr-g++ -platformar=$PWD/toolchains/arduino-nightly/hardware/tools/avr/bin/avr-ar -platformcflags=\"-I$PWD/toolchains/arduino-nightly/hardware/arduino/avr/cores/arduino\" -platformcflags=\"-I$PWD/toolchains/arduino-nightly/hardware/arduino/avr/variants/standard\" && make && make install"
    - $PWD/bin/bin/muletool -compile tests/test01-muleapplication-test.cpp && $PWD/bin/bin/muletool -link tests/test01-muleapplication-test.o && mv -v a.out run-test01
    - $PWD/bin/bin/muletool -compile tests/test04-mulesensor-trigger.cpp && $PWD/bin/bin/muletool -link tests/test04-mulesensor-trigger.o && mv -v a.out run-test04
    - rm -r -f run-test* arduinoplatform-gcc-builddir/ bin/
    
