before_script:
  - apt-get update -qq && apt-get install -y -qq ftjam gcc g++ wget bsdtar clang libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386
  - mkdir -v toolchains
  - sh -c "cd toolchains && wget http://releases.linaro.org/archive/15.06/components/toolchain/binaries/4.8/arm-linux-gnueabi/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi.tar.xz && tar -xvJf gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi.tar.xz"
  - sh -c "cd toolchains && wget https://sourcery.mentor.com/GNUToolchain/package12225/public/arm-none-linux-gnueabi/arm-2013.11-33-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2 && tar -xvjf arm-2013.11-33-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2 && mv -v arm-2013.11/ codesourcery-gcc/"
  - ftjam -v
  - gcc -dumpversion
  - gcc -v

dummyplatform_and_tests:
  script:
    - ftjam -sDEBUG=yes -sMULETARGET=dummy -sCC=/usr/bin/gcc -sCXX=/usr/bin/g++ -q all
    - /usr/bin/g++ -g -Os tests/test01-muleapplication-test.cpp libMule.a -Isrc -o tests/run-test01
    - ./tests/run-test01
    - /usr/bin/g++ -g -Os tests/test02-mulefile-currentdirectory.cpp libMule.a -Isrc -o tests/run-test02
    - touch ./popcorn.txt
    - sh -c "echo \"Testing 1 2 3\" > popcorn.txt"
    - cat ./popcorn.txt
    - ./tests/run-test02
    - sh -c "if test -e \"./popcorn.txt\"; then rm -r -f popcorn.txt; fi"
    - ./tests/run-test02
    - ftjam -sDEBUG=yes -sMULETARGET=dummy -sCC=/usr/bin/gcc -sCXX=/usr/bin/g++ -q clean
    - rm -r -f ./tests/run-test0* ./src/core/muleconfig.*

legoev3platform_and_tests:
  script:
    - ftjam -sDEBUG=yes -sMULETARGET=legoev3 -sMULECOMPILERFLAGS="-march=armv5 -mtune=arm9 -static-libstdc++ -static-libgcc" -sCC=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc -sCXX=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -sLINK=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -sLINKFLAGS="-march=armv5 -mtune=arm9 -static-libstdc++ -static-libgcc" -q all
    - $PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -g -Os tests/test01-muleapplication-test.cpp libMule.a -Isrc -o tests/run-test01 -static-libstdc++ -static-libgcc -Isrc/3rdparty/EV3-API-master/API
    - $PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -g -Os tests/test02-mulefile-currentdirectory.cpp libMule.a -Isrc -o tests/run-test02 -static-libstdc++ -static-libgcc -Isrc/3rdparty/EV3-API-master/API
    - ftjam -sDEBUG=yes -sMULETARGET=legoev3 -sMULECOMPILERFLAGS="-march=armv5 -mtune=arm9 -static-libstdc++ -static-libgcc" -sCC=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc -sCXX=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -sLINK=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -sLINKFLAGS="-march=armv5 -mtune=arm9 -static-libstdc++ -static-libgcc" -q clean
    - rm -r -f -v tests/run-test0* src/core/muleconfig.*

dummyplatform_and_tests_llvm:
  script:
    - ftjam -sDEBUG=yes -sMULETARGET=dummy -sCC=/usr/bin/clang -sCXX=/usr/bin/clang++ -q all
    - /usr/bin/clang++ -g -Os tests/test01-muleapplication-test.cpp libMule.a -Isrc -o tests/run-test01
    - ./tests/run-test01
    - /usr/bin/clang++ -g -Os tests/test02-mulefile-currentdirectory.cpp libMule.a -Isrc -o tests/run-test02
    - ./tests/run-test02
    - ftjam -sDEBUG=yes -sMULETARGET=dummy -sCC=/usr/bin/clang -sCXX=/usr/bin/clang++ -q clean
    - rm -r -f ./tests/run-test0* ./src/core/muleconfig.*

legoev3platform_and_tests_codesourcerytoolchain:
  script:
    - ftjam -sDEBUG=yes -sMULETARGET=legoev3 -sMULECOMPILERFLAGS="-march=armv4t  -static-libstdc++ -static-libgcc" -sCC=$PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-gcc -sCXX=$PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-c++ -sLINK=$PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-c++ -sLINKFLAGS="-march=armv4t  -static-libstdc++ -static-libgcc" -q all
    - $PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-c++ -g -Os tests/test01-muleapplication-test.cpp libMule.a -Isrc -o tests/run-test01 -static-libstdc++ -static-libgcc -Isrc/3rdparty/EV3-API-master/API
    - $PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-c++ -g -Os tests/test02-mulefile-currentdirectory.cpp libMule.a -Isrc -o tests/run-test02 -static-libstdc++ -static-libgcc -Isrc/3rdparty/EV3-API-master/API
    - ftjam -sDEBUG=yes -sMULETARGET=legoev3 -sMULECOMPILERFLAGS="-march=armv4t  -static-libstdc++ -static-libgcc" -sCC=$PWD/toolchains/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc -sCXX=$PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-c++ -sLINK=$PWD/toolchains/codesourcery-gcc/bin/arm-none-linux-gnueabi-c++ -sLINKFLAGS="-march=armv4t  -static-libstdc++ -static-libgcc" -q clean
    - rm -r -f -v tests/run-test0* src/core/muleconfig.*
